let data = [
  {
    name: "Dress 1",
    slug: "Dress1",
    img: "/images/1.jpeg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: 400,
    ratings: "5",
    numberOfRatings: "120",
    stock: 3,
    model: "women",
    coupon: "abc",
    allcupon: "sujan",
    discount: 20,
    totalSales: 100,
    brand: "HighX",
  },
  {
    name: "Dress 2",
    slug: "Dress2",
    img: "/images/2.jpeg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: 600,
    ratings: "3.5",
    numberOfRatings: "130",
    stock: 2,
    model: "men",
    coupon: "abcd",
    allcupon: "sujan",
    discount: 25,
    totalSales: 200,
    brand: "LowX",
  },
  {
    name: "Dress 3",
    slug: "Dress3",
    img: "/images/3.jpeg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: 800,
    ratings: "4",
    numberOfRatings: "140",
    stock: 0,
    model: "women",
    coupon: "abcde",
    allcupon: "sujan",
    discount: 10,
    totalSales: 30,
    brand: "LowX",
  },
  {
    name: "Dress 4",
    slug: "Dress4",
    img: "/images/4.jpeg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: 900,
    ratings: "4.5",
    numberOfRatings: "100",
    stock: 2,
    model: "men",
    coupon: "abcdef",
    allcupon: "sujan",
    discount: 40,
    totalSales: 300,
    brand: "LowT",
  },

  {
    name: "Dress 5",
    slug: "Dress5",
    img: "/images/2.jpeg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: 400,
    ratings: "5",
    numberOfRatings: "120",
    stock: 10,
    model: "men",
    coupon: "",
    allcupon: "sujan",
    discount: 0,
    totalSales: 50,
    brand: "LowT",
  },

  {
    name: "Dress 6",
    slug: "Dress6",
    img: "/images/1.jpeg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: 400,
    ratings: "5",
    numberOfRatings: "120",
    stock: 10,
    model: "men",
    coupon: "",
    allcupon: "sujan",
    discount: 0,
    totalSales: 50,
    brand: "HighX",
  },
  {
    name: "Dress 7",
    slug: "Dress 7",
    img: "/images/7.jpeg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: 400,
    ratings: "5",
    numberOfRatings: "120",
    stock: 10,
    model: "children",
    coupon: "",
    allcupon: "sujan",
    discount: 0,
    totalSales: 50,
    brand: "HighY",
  },
  {
    name: "Dress 8",
    slug: "Dress 8",
    img: "/images/8.jpeg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: 800,
    ratings: "5",
    numberOfRatings: "120",
    stock: 10,
    model: "children",
    coupon: "",
    allcupon: "sujan",
    discount: 0,
    totalSales: 50,
    brand: "HighX",
  },
];

export default data;
